server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://115.22.91.219:3377/muesli_music_test?serverTimezone=UTC&characterEncoding=UTF-8
      username: muesli_music_test
      password: muesli_music_test

  flyway:
    user: muesli_music_test
    password: muesli_music_test
    schemas: muesli_music_test
    url: jdbc:mariadb://115.22.91.219:3377/muesli_music_test?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true
    baseline-on-migrate: true


#  h2:
#    console:
#      enabled: true
#      path: /h2-console

logging:
  config: classpath:logback-local.xml

