###  Album 조회
GET http://localhost:8080/api/v1/albums/1809
Content-Type: application/json
Authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9

###  Artist 조회
GET http://localhost:8080/api/v1/artists/1113
Content-Type: application/json
authorization:Bearer d4243743538e9b86c862aee116f5dd411fbd300d

###  Track 조회
GET http://localhost:8080/api/v1/tracks/42860
Content-Type: application/json
Authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9

### 회원가입
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "email": "jinhun389212@gmail.com",
  "password": "12345678",
  "username": "테스트",
  "phoneNumber": "010-0000-0000"
}

### 로그인
POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "email" : "jinhun3892@gmail.com",
  "password": "12345678"
}

### 좋아요
POST http://localhost:8080/api/v1/likes/like
authorization:Bearer 247cc06dbedd6ac043466a37b0e001c84ec2b2ae
Content-Type: application/json

{
  "likeableId" : 1545,
  "likeableType" : "App\\Track"
}

### 좋아요 취소
POST http://localhost:8080/api/v1/likes/disLike/697
authorization:Bearer afa0a93dfb7edec9ad7ea9c775cdd1d76d8f9ed7
Content-Type: application/json

### 좋아요 리스트(트랙)
GET http://localhost:8080/api/v1/tracks/likeables
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

### 좋아요 리스트(아티스트)
GET http://localhost:8080/api/v1/artists/likeables
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

### 좋아요 리스트(앨범)
GET http://localhost:8080/api/v1/albums/likeables
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

### 플레이 리스트 생성
POST http://localhost:8080/api/v1/playlists/create
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

{
  "name": "실험용플레이리스트5!!",
  "description": "테스트 설명글",
  "isPublic": 1
}

### 플레이 리스트 수정
POST http://localhost:8080/api/v1/playlists/update
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

{
  "id": 80,
  "name": "실험용플레이리스트3!!!!!!",
  "description": "테스트 설명글!!",
  "isPublic": 0
}

### 플레이 리스트 삭제
GET http://localhost:8080/api/v1/playlists/delete/77
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

### 플레이 리스트 조회
GET http://localhost:8080/api/v1/playlists/6?page=1&size=100
authorization:Bearer 247cc06dbedd6ac043466a37b0e001c84ec2b2ae
Content-Type: application/json

### 플레이 리스트 트랙 추가
POST http://localhost:8080/api/v1/playlists/addTrack
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

{
  "playlistId" : 80,
  "trackList" : [42860,42861,42862,42863,42865,42866]
}

### 플레이 리스트 트랙 삭제
POST http://localhost:8080/api/v1/playlists/removeTrack
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

{
  "playlistId" : 80,
  "trackList" : [42861]
}