###  Album 조회
GET http://localhost:8080/api/v1/album/20
Content-Type: application/json
Authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9

###  Artist 조회
GET http://localhost:8080/api/v1/artist/20
Content-Type: application/json
authorization:Bearer d4243743538e9b86c862aee116f5dd411fbd300d

###  Track 조회
GET http://localhost:8080/api/v1/track/2
Content-Type: application/json
Authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9

### 회원가입
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "email": "coby1997@naver.com",
  "password": "12345678",
  "username": "재욱",
  "phoneNumber": "010-8483-7522",
  "gender" : "M",
  "birthday" : "1997-07-14"
}

### 로그인
POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "email" : "hun9003@naver.com",
  "password": "12345678"
}

### 좋아요
POST http://localhost:8080/api/v1/like
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

{
  "likeableId" : 1113,
  "likeableType" : "Artist"
}

### 좋아요 상태변경
PUT http://localhost:8080/api/v1/like
authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJodW45MDAzQG5hdmVyLmNvbSIsImV4cCI6MTY1NzcwMzI2OX0.7euBqSP_yAg9KwOO9dlHYkXocBz9-ABwYaQid8QaXEk
Content-Type: application/json

{
  "id": 840
}


### 좋아요 리스트(트랙)
GET http://localhost:8080/api/v1/track/likeables
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 좋아요 리스트(아티스트)
GET http://localhost:8080/api/v1/artist/likeables
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 좋아요 리스트(앨범)
GET http://localhost:8080/api/v1/album/likeables
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 플레이 리스트 생성
POST http://localhost:8080/api/v1/playlist
authorization:Bearer nqgHmPDyXTcwia2PlL94pnEtZcxP15QQwKIb3mjG
Content-Type: application/json

{
  "name": "실험용플레이리스트12!!",
  "description": "테스트 설명글",
  "isPublic": 1
}

### 플레이 리스트 수정
PUT http://localhost:8080/api/v1/playlist/90
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

{
  "name": "실험용플레이리스트12!!!!!!",
  "description": "테스트 설명글!!",
  "isPublic": 1,
  "trackList" : [42859, 42863, 42865, 42866, 42861, 42870]
}

### 플레이 리스트 삭제
DELETE http://localhost:8080/api/v1/playlist/85
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 플레이 리스트 조회
GET http://localhost:8080/api/v1/playlist/1?page=1&size=100
authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJodW45MDAzQG5hdmVyLmNvbSIsImV4cCI6MTY1NzAwNjc3Nn0.GGBYjianLD_1o-roUpi0e
Content-Type: application/json

### 플레이 리스트 트랙 추가
PUT http://localhost:8080/api/v1/playlist/track/90
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

{
  "trackList" : [42860,42861,42862,42863,42865,42866]
}

### 플레이 리스트 트랙 삭제
DELETE http://localhost:8080/api/v1/playlist/track/87
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

{
  "playlistId" : 80,
  "trackList" : [42861]
}

### 내 플레이리스트 조회
GET http://localhost:8080/api/v1/playlist/my
authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJodW45MDAzQG5hdmVyLmNvbSIsImV4cCI6MTY1NzAwNjc3Nn0.GGBYjianLD_1o-roUpi0e_P1Nb-ujSbpaxguwOhhtP
Content-Type: application/json

### 좋아요 리스트(플레이 리스트)
GET http://localhost:8080/api/v1/playlist/likeables?page=1&size=100
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### TOP100
GET http://localhost:8080/api/v1/track/rank/week?date=2022-06-28
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### TOP100 레이아웃 조회
GET http://localhost:8080/api/v1/track/rank/layout
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### 아이템 리스트 좋아요 조회
GET http://localhost:8080/api/v1/like/show?type=artist&ids=1113,3212,3214,5234
Content-Type: application/json

### 최신곡
GET http://localhost:8080/api/v1/track/new?page=1
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### 최신앨범
GET http://localhost:8080/api/v1/album/new?page=1
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### 최근 들은 곡
GET http://localhost:8080/api/v1/track/history?page=1
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 트랙 검색 결과 페이지
GET http://localhost:8080/api/v1/search/track?keyword=명탐정코난&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 앨범 검색 결과 페이지
GET http://localhost:8080/api/v1/search/album?keyword=ad&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 아티스트 검색 결과 페이지
GET http://localhost:8080/api/v1/search/artist?keyword=아&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 가사 검색 결과 페이지
GET http://localhost:8080/api/v1/search/lyrics?keyword=아&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 전체 검색 결과 페이지
GET http://localhost:8080/api/v1/search/all?keyword=head&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 키워드 자동완성
GET http://localhost:8080/api/v1/search?keyword=a
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 플레이어 음원 재생 키
GET http://localhost:8080/api/v1/player/42860
authorization:Bearer vtKYrQBBJM8a7Qxn3R5J8gCShkCcLTcKcoqbRvAZ
Content-Type: application/json


### 장르 전체 조회
GET http://localhost:8080/api/v1/genre
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 장르 개별 조회
GET http://localhost:8080/api/v1/genre/1
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 장르별 곡 리스트 조회
GET http://localhost:8080/api/v1/genre/2/track
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 비밀번호 변경
PUT http://localhost:8080/api/v1/user/modify/password
authorization:Bearer sAWkGiJ3EJy9eiVDl0a7nJMC4KDlFedJxghno2k7
Content-Type: application/json

{
  "password" : "12345677",
  "newPassword" : "12345678"
}

### 큐레이팅(임시)
GET http://localhost:8080/api/v1/channel
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 구글 엑세스 검증
GET http://localhost:8080/api/v1/user/login/social?auth_type=google&access_token=ya29.a0ARrdaM8v0tMwdnDcF565cYYJexvtqHjfusuccRmlppo9DBnaDkRYMDzHneLGk3zXhj96avpZOLv8mORsOnmkL3vAAOTiA9_P4Vd1hFIgWaqYU_4M-iMvwtiIEADR4r4Mpfot9QlO4xGK_JuLHFLnXTsS0OQR
Content-Type: application/json

### 곡 재생
POST http://localhost:8080/api/v1/player/1
authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJodW45MDAzQG5hdmVyLmNvbSIsImV4cCI6MTY1ODQ3OTE2N30.MnfMneHXHV6e0sR5VcU7M4CHx8W2MT4uJRPDAQCOR0o
Content-Type: application/json