###  Album 조회
GET http://localhost:8080/api/v1/albums/1809
Content-Type: application/json
Authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9

###  Artist 조회
GET http://localhost:8080/api/v1/artists/1113
Content-Type: application/json
authorization:Bearer d4243743538e9b86c862aee116f5dd411fbd300d

###  Track 조회
GET http://localhost:8080/api/v1/tracks/42860
Content-Type: application/json
Authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9

### 회원가입
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "email": "jinhun389212@gmail.com",
  "password": "12345678",
  "username": "테스트",
  "phoneNumber": "010-0000-0000"
}

### 로그인
POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "email" : "hun9003@naver.com",
  "password": "wlsgns12"
}

### 좋아요
POST http://localhost:8080/api/v1/likes
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

{
  "likeableId" : 42860,
  "likeableType" : "Track"
}

### 좋아요 상태변경
PUT http://localhost:8080/api/v1/likes/840
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 좋아요 리스트(트랙)
GET http://localhost:8080/api/v1/tracks/likeables
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 좋아요 리스트(아티스트)
GET http://localhost:8080/api/v1/artists/likeables
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### 좋아요 리스트(앨범)
GET http://localhost:8080/api/v1/albums/likeables?page=1&size=3
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### 플레이 리스트 생성
POST http://localhost:8080/api/v1/playlists
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

{
  "name": "실험용플레이리스트5!!",
  "description": "테스트 설명글",
  "isPublic": 1
}

### 플레이 리스트 수정
PUT http://localhost:8080/api/v1/playlists/85
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

{
  "name": "실험용플레이리스트3!!!!!!",
  "description": "테스트 설명글!!",
  "isPublic": 0,
  "trackList" : [42859, 42863, 42865, 42866, 42861, 42870]
}

### 플레이 리스트 삭제
DELETE http://localhost:8080/api/v1/playlists/85
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 플레이 리스트 조회
GET http://localhost:8080/api/v1/playlists/85?page=1&size=100
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 플레이 리스트 트랙 추가
PUT http://localhost:8080/api/v1/playlists/tracks/85
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

{
  "trackList" : [42860,42861,42862,42863,42865,42866]
}

### 플레이 리스트 트랙 삭제
DELETE http://localhost:8080/api/v1/playlists/tracks/87
authorization:Bearer 268a1d75422c1bb841821806557a03a2ac55a4f9
Content-Type: application/json

{
  "playlistId" : 80,
  "trackList" : [42861]
}

### 내 플레이리스트 조회
GET http://localhost:8080/api/v1/playlists/my?page=1&size=100
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 좋아요 리스트(플레이 리스트)
GET http://localhost:8080/api/v1/playlists/likeables?page=1&size=100
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### TOP100
GET http://localhost:8080/api/v1/tracks/rank?type=month&genre=1
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### TOP100 레이아웃 조회
GET http://localhost:8080/api/v1/tracks/rank/layout
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### 아이템 리스트 좋아요 조회
POST http://localhost:8080/api/v1/likes/show
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

{
  "type" : "artist",
  "ids" : [1113, 3212, 3214, 5234]
}

### 최신곡
GET http://localhost:8080/api/v1/tracks/new?page=1
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### 최신앨범
GET http://localhost:8080/api/v1/albums/new?page=1
authorization:Bearer WcXJlhpnSZUKjhhg0sEAqY3JxW6mnqsIRNwJb91n
Content-Type: application/json

### 최근 들은 곡
GET http://localhost:8080/api/v1/tracks/history?page=1
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 트랙 검색 결과 페이지
GET http://localhost:8080/api/v1/search/tracks?keyword=명탐정코난&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 앨범 검색 결과 페이지
GET http://localhost:8080/api/v1/search/albums?keyword=명탐정코난&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 아티스트 검색 결과 페이지
GET http://localhost:8080/api/v1/search/artists?keyword=아&page=1&size=10

authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 가사 검색 결과 페이지
GET http://localhost:8080/api/v1/search/lyrics?keyword=아&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 전체 검색 결과 페이지
GET http://localhost:8080/api/v1/search/all?keyword=아&page=1&size=10
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 키워드 자동완성
GET http://localhost:8080/api/v1/search?keyword=며
authorization:Bearer VFLZuEcx1BQVn5F5LlHPSryAfr7KT4wwgdvq9HLw
Content-Type: application/json

### 플레이어 음원 재생 키
GET http://localhost:8080/api/v1/player/42860
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json

### 장르 키워드로 조회
GET http://localhost:8080/api/v1/genre/search/1?keyword=나
authorization:Bearer jikdN1Eb4PrBpgZmDAJ3JuM8aScRl2CiKSENpVzo
Content-Type: application/json